[package]
name = "rustwasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
serde = "1.0.225"
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.103"

[dev-dependencies]
console_error_panic_hook = "0.1.7"
